### PR TITLE
revert impeller

### PR DESCRIPTION
**Pull request by abdelaziz-mahdy**
should fix https://github.com/wang-bin/fvp/issues/101

### CODE REVIEW

**Comment by wang-bin** [comment]
I wonder if we can detect whether impeller is enabled or not in java or dart. If impeller is enabled, use SurfaceProducer, otherwise use SurfaceTextureEntry.

**Comment by abdelaziz-mahdy** [comment]
i like that idea, but it needs some research to find the flag they use, if i was able to find it will update the pr

**Comment by abdelaziz-mahdy** [comment]
https://github.com/flutter/engine/blob/c8b4446439af586e29354b307ad46ccda79c35f9/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java#L188 i think this can be used as a reference

**Comment by wang-bin** [comment]
> https://github.com/flutter/engine/blob/c8b4446439af586e29354b307ad46ccda79c35f9/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java#L188 i think this can be used as a reference

no, it returns different SurfaceProducer depending on system version.

I think we can check 'io.flutter.embedding.android.EnableImpeller' in AndroidManifest.xml like this https://github.com/flutter/engine/blob/3.23.0-12.0.pre/shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java#L343

**Comment by wang-bin** [comment]
i can detect impeller from androidmanifest.xml: https://github.com/wang-bin/fvp/compare/master...impeller

I'm using flutter 3.22,  video is blank if i enable impeller in xml, iirc flutter 3.19 impeller works correctly, can you test it?

**Comment by abdelaziz-mahdy** [comment]
i am still facing the crash problem, i guess its related to impller being enabled, not a problem from your side, 

also in your code you dont detect if the user launched with `--enable-impeller` right

**Comment by abdelaziz-mahdy** [comment]
i tried video_player example without fvp and got no crash, with impller on and off, 

but fvp example crashes. 
but when i set register with to this it doesnt 
```
  fvp.registerWith(options: {
        'platforms': ['windows', 'linux'], 

  });
```

**Comment by wang-bin** [comment]
can you share your example code or apk?

**Comment by wang-bin** [comment]
> also in your code you dont detect if the user launched with --enable-impeller right

I guess so

**Comment by abdelaziz-mahdy** [comment]
> can you share your example code or apk?

i can share the apk since its fvp example, do you know how to extract the crash logs? just for general debugging

**Comment by abdelaziz-mahdy** [comment]
https://easyupload.io/n96qnu is the apk

**Comment by wang-bin** [comment]
`adb logcat |tee test.log` and stop after crash, you can also save the crash log with full backtrace and remove others like this
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/oriole/oriole:14/AP2A.240605.024/11860263:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
Timestamp: 2024-06-23 00:32:29.843187339+0300
Process uptime: 125s
Cmdline: com.zcreations.anime_here
pid: 28128, tid: 28208, name: 1.ui  >>> com.zcreations.anime_here <<<
uid: 10289
tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000000
Cause: null pointer dereference
    x0  b400007270452c20  x1  b4000072a02f2ff0  x2  0000000000000010  x3  0000006f072a77d9
    x4  0000000000000000  x5  b400007270452c20  x6  b4000072a02f2ff0  x7  0000000000000010
    x8  b400007330c32c10  x9  0000000000000000  x10 0000000000000005  x11 0000000000003590
    x12 000000007fffffff  x13 000000000241fe04  x14 000000000241fe04  x15 0000007157115300
    x16 0000000000000000  x17 b400007330c33388  x18 0000007156140000  x19 00000071c8c32a94
    x20 0000007157115df8  x21 b400007330c32c10  x22 0000006f00008081  x23 000e26e9399d0e9b
    x24 0000006f00008081  x25 0000007156f34000  x26 b400007330c32c10  x27 0000006f09a2e160
    x28 000000080000006f  x29 0000007157115318
    lr  000000714f187fd8  sp  0000007157115300  pc  0000000000000000  pst 0000000060001000
2 total frames
backtrace:
      #00 pc 0000000000000000  <unknown>
      #01 pc 0000000000007fd4  [anon:dart-code]
Lost connection to device.
```

Then run `ndk-stack -sym mdk-sdk/lib/arm64-v8a -dump test.log, then you will see source file and line number

**Comment by abdelaziz-mahdy** [comment]
this where i was lost on how to debug `ndk-stack` thank you very much, can you check the apk and let me know if the crash happens for you or not?

**Comment by wang-bin** [comment]
You mdk is too old, please upgrade to the latest nightly build version. It crash in flutter, so can't see line number
```

20:12:14.442 17176-17176 DEBUG            A  *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
20:12:14.442 17176-17176 DEBUG            A  Build fingerprint: 'Redmi/mondrian/mondrian:14/UKQ1.230804.001/V816.0.6.0.UMNCNXM:user/release-keys'
20:12:14.442 17176-17176 DEBUG            A  Revision: '0'
20:12:14.442 17176-17176 DEBUG            A  ABI: 'arm64'
20:12:14.442 17176-17176 DEBUG            A  Timestamp: 2024-06-25 20:12:13.906852859+0800
20:12:14.443 17176-17176 DEBUG            A  Process uptime: 1074s
20:12:14.443 17176-17176 DEBUG            A  Cmdline: com.mediadevkit.fvp_example
20:12:14.443 17176-17176 DEBUG            A  pid: 10224, tid: 17082, name: 1.ui  >>> com.mediadevkit.fvp_example <<<
20:12:14.443 17176-17176 DEBUG            A  uid: 10565
20:12:14.443 17176-17176 DEBUG            A  tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
20:12:14.443 17176-17176 DEBUG            A  pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
20:12:14.443 17176-17176 DEBUG            A  signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000000
20:12:14.443 17176-17176 DEBUG            A  Cause: null pointer dereference
20:12:14.443 17176-17176 DEBUG            A      x0  b400006fde666280  x1  b400007053f27f00  x2  0000000000000010  x3  0000000000000010
20:12:14.443 17176-17176 DEBUG            A      x4  0000006e00009cb1  x5  0000000000000004  x6  0000000000000000  x7  0000000000000000
20:12:14.443 17176-17176 DEBUG            A      x8  b400007053f27f00  x9  0000000000000000  x10 0000000000000005  x11 0000007046c9cf20
20:12:14.443 17176-17176 DEBUG            A      x12 0000000000000005  x13 0000000000000100  x14 000000000000ffc0  x15 0000006feba233b0
20:12:14.444 17176-17176 DEBUG            A      x16 0000000000000000  x17 b400006fdd1f2578  x18 0000006feb2a4000  x19 0000006fe4f8cb90
20:12:14.444 17176-17176 DEBUG            A      x20 0000006feba23968  x21 b400006fde2a04c0  x22 0000006e00008081  x23 0000006feba238a0
20:12:14.444 17176-17176 DEBUG            A      x24 0000006e00008081  x25 0000006feb842000  x26 b400006fdd1f1e00  x27 0000006e00580080
20:12:14.444 17176-17176 DEBUG            A      x28 000000080000006e  x29 0000006feba233b8
20:12:14.444 17176-17176 DEBUG            A      lr  0000006fe4d6e620  sp  0000006feba233b0  pc  0000000000000000  pst 0000000060001800
20:12:14.444 17176-17176 DEBUG            A  28 total frames
20:12:14.444 17176-17176 DEBUG            A  backtrace:
20:12:14.444 17176-17176 DEBUG            A        #00 pc 0000000000000000  <unknown>
20:12:14.444 17176-17176 DEBUG            A        #01 pc 00000000001a161c  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
20:12:14.444 17176-17176 DEBUG            A        #02 pc 00000000003bfb80  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
20:12:14.444 17176-17176 DEBUG            A        #03 pc 00000000003bf8f0  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
20:12:14.444 17176-17176 DEBUG            A        #04 pc 00000000003bf6ec  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
20:12:14.444 17176-17176 DEBUG            A        #05 pc 0000000000293b9c  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
20:12:14.444 17176-17176 DEBUG            A        #06 pc 00000000002938c4  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
20:12:14.445 17176-17176 DEBUG            A        #07 pc 00000000001bf938  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
20:12:14.445 17176-17176 DEBUG            A        #08 pc 00000000001bf760  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
20:12:14.445 17176-17176 DEBUG            A        #09 pc 00000000001bf6e8  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
20:12:14.445 17176-17176 DEBUG            A        #10 pc 0000000000423884  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
20:12:14.445 17176-17176 DEBUG            A        #11 pc 00000000001bed9c  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
20:12:14.445 17176-17176 DEBUG            A        #12 pc 00000000001a3db0  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
20:12:14.445 17176-17176 DEBUG            A        #13 pc 0000000000845c50  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
20:12:14.445 17176-17176 DEBUG            A        #14 pc 0000000000851194  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
20:12:14.445 17176-17176 DEBUG            A        #15 pc 0000000000856138  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
20:12:14.445 17176-17176 DEBUG            A        #16 pc 00000000007b6948  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
20:12:14.445 17176-17176 DEBUG            A        #17 pc 00000000008085fc  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
20:12:14.445 17176-17176 DEBUG            A        #18 pc 0000000000474bf4  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
20:12:14.445 17176-17176 DEBUG            A        #19 pc 0000000000478784  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
20:12:14.445 17176-17176 DEBUG            A        #20 pc 0000000000018dc8  /system/lib64/libutils.so (android::Looper::pollInner(int)+1252) (BuildId: f77e8a7cc4315a777d187d5c714e8155)
20:12:14.445 17176-17176 DEBUG            A        #21 pc 0000000000018880  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+124) (BuildId: f77e8a7cc4315a777d187d5c714e8155)
20:12:14.445 17176-17176 DEBUG            A        #22 pc 000000000001a188  /system/lib64/libandroid.so (ALooper_pollOnce+104) (BuildId: 5acb3dcccd51dac4b4f16a53858cc75e)
20:12:14.445 17176-17176 DEBUG            A        #23 pc 0000000000478890  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
20:12:14.445 17176-17176 DEBUG            A        #24 pc 0000000000476938  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
20:12:14.445 17176-17176 DEBUG            A        #25 pc 000000000047672c  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
20:12:14.445 17176-17176 DEBUG            A        #26 pc 00000000000fd134  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: 1e3ca19bcae05c01b019c85f3f422e56)
20:12:14.446 17176-17176 DEBUG            A        #27 pc 0000000000096ae4  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 1e3ca19bcae05c01b019c85f3f422e56)
20:12:14.487   984-991   Tombst...onitor  W  Detected deletd file: tombstone_11
20:12:14.487  2498-17181 DropBo...ervice  I  add tag=data_app_native_crash isTagEnabled=true flags=0x2
```

**Comment by abdelaziz-mahdy** [comment]
> You mdk is too old, please upgrade to the latest nightly build version. It crash in flutter, so can't see line number
> 
> ```
> 
> 20:12:14.442 17176-17176 DEBUG            A  *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> 20:12:14.442 17176-17176 DEBUG            A  Build fingerprint: 'Redmi/mondrian/mondrian:14/UKQ1.230804.001/V816.0.6.0.UMNCNXM:user/release-keys'
> 20:12:14.442 17176-17176 DEBUG            A  Revision: '0'
> 20:12:14.442 17176-17176 DEBUG            A  ABI: 'arm64'
> 20:12:14.442 17176-17176 DEBUG            A  Timestamp: 2024-06-25 20:12:13.906852859+0800
> 20:12:14.443 17176-17176 DEBUG            A  Process uptime: 1074s
> 20:12:14.443 17176-17176 DEBUG            A  Cmdline: com.mediadevkit.fvp_example
> 20:12:14.443 17176-17176 DEBUG            A  pid: 10224, tid: 17082, name: 1.ui  >>> com.mediadevkit.fvp_example <<<
> 20:12:14.443 17176-17176 DEBUG            A  uid: 10565
> 20:12:14.443 17176-17176 DEBUG            A  tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
> 20:12:14.443 17176-17176 DEBUG            A  pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
> 20:12:14.443 17176-17176 DEBUG            A  signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000000
> 20:12:14.443 17176-17176 DEBUG            A  Cause: null pointer dereference
> 20:12:14.443 17176-17176 DEBUG            A      x0  b400006fde666280  x1  b400007053f27f00  x2  0000000000000010  x3  0000000000000010
> 20:12:14.443 17176-17176 DEBUG            A      x4  0000006e00009cb1  x5  0000000000000004  x6  0000000000000000  x7  0000000000000000
> 20:12:14.443 17176-17176 DEBUG            A      x8  b400007053f27f00  x9  0000000000000000  x10 0000000000000005  x11 0000007046c9cf20
> 20:12:14.443 17176-17176 DEBUG            A      x12 0000000000000005  x13 0000000000000100  x14 000000000000ffc0  x15 0000006feba233b0
> 20:12:14.444 17176-17176 DEBUG            A      x16 0000000000000000  x17 b400006fdd1f2578  x18 0000006feb2a4000  x19 0000006fe4f8cb90
> 20:12:14.444 17176-17176 DEBUG            A      x20 0000006feba23968  x21 b400006fde2a04c0  x22 0000006e00008081  x23 0000006feba238a0
> 20:12:14.444 17176-17176 DEBUG            A      x24 0000006e00008081  x25 0000006feb842000  x26 b400006fdd1f1e00  x27 0000006e00580080
> 20:12:14.444 17176-17176 DEBUG            A      x28 000000080000006e  x29 0000006feba233b8
> 20:12:14.444 17176-17176 DEBUG            A      lr  0000006fe4d6e620  sp  0000006feba233b0  pc  0000000000000000  pst 0000000060001800
> 20:12:14.444 17176-17176 DEBUG            A  28 total frames
> 20:12:14.444 17176-17176 DEBUG            A  backtrace:
> 20:12:14.444 17176-17176 DEBUG            A        #00 pc 0000000000000000  <unknown>
> 20:12:14.444 17176-17176 DEBUG            A        #01 pc 00000000001a161c  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
> 20:12:14.444 17176-17176 DEBUG            A        #02 pc 00000000003bfb80  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
> 20:12:14.444 17176-17176 DEBUG            A        #03 pc 00000000003bf8f0  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
> 20:12:14.444 17176-17176 DEBUG            A        #04 pc 00000000003bf6ec  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
> 20:12:14.444 17176-17176 DEBUG            A        #05 pc 0000000000293b9c  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
> 20:12:14.444 17176-17176 DEBUG            A        #06 pc 00000000002938c4  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
> 20:12:14.445 17176-17176 DEBUG            A        #07 pc 00000000001bf938  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
> 20:12:14.445 17176-17176 DEBUG            A        #08 pc 00000000001bf760  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
> 20:12:14.445 17176-17176 DEBUG            A        #09 pc 00000000001bf6e8  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
> 20:12:14.445 17176-17176 DEBUG            A        #10 pc 0000000000423884  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
> 20:12:14.445 17176-17176 DEBUG            A        #11 pc 00000000001bed9c  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
> 20:12:14.445 17176-17176 DEBUG            A        #12 pc 00000000001a3db0  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libapp.so (BuildId: 083986ec0822c1fe208427165b704f39)
> 20:12:14.445 17176-17176 DEBUG            A        #13 pc 0000000000845c50  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
> 20:12:14.445 17176-17176 DEBUG            A        #14 pc 0000000000851194  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
> 20:12:14.445 17176-17176 DEBUG            A        #15 pc 0000000000856138  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
> 20:12:14.445 17176-17176 DEBUG            A        #16 pc 00000000007b6948  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
> 20:12:14.445 17176-17176 DEBUG            A        #17 pc 00000000008085fc  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
> 20:12:14.445 17176-17176 DEBUG            A        #18 pc 0000000000474bf4  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
> 20:12:14.445 17176-17176 DEBUG            A        #19 pc 0000000000478784  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
> 20:12:14.445 17176-17176 DEBUG            A        #20 pc 0000000000018dc8  /system/lib64/libutils.so (android::Looper::pollInner(int)+1252) (BuildId: f77e8a7cc4315a777d187d5c714e8155)
> 20:12:14.445 17176-17176 DEBUG            A        #21 pc 0000000000018880  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+124) (BuildId: f77e8a7cc4315a777d187d5c714e8155)
> 20:12:14.445 17176-17176 DEBUG            A        #22 pc 000000000001a188  /system/lib64/libandroid.so (ALooper_pollOnce+104) (BuildId: 5acb3dcccd51dac4b4f16a53858cc75e)
> 20:12:14.445 17176-17176 DEBUG            A        #23 pc 0000000000478890  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
> 20:12:14.445 17176-17176 DEBUG            A        #24 pc 0000000000476938  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
> 20:12:14.445 17176-17176 DEBUG            A        #25 pc 000000000047672c  /data/app/~~hoa8R5AV6nKT53ZzFaQ1Rw==/com.mediadevkit.fvp_example-rLpWe-CXnfc3Vv4PJ3EUJw==/lib/arm64/libflutter.so (BuildId: e05edcf1368609668cf1873a167462cbcf923136)
> 20:12:14.445 17176-17176 DEBUG            A        #26 pc 00000000000fd134  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: 1e3ca19bcae05c01b019c85f3f422e56)
> 20:12:14.446 17176-17176 DEBUG            A        #27 pc 0000000000096ae4  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 1e3ca19bcae05c01b019c85f3f422e56)
> 20:12:14.487   984-991   Tombst...onitor  W  Detected deletd file: tombstone_11
> 20:12:14.487  2498-17181 DropBo...ervice  I  add tag=data_app_native_crash isTagEnabled=true flags=0x2
> ```

i did run flutter clean and flutter pub clean, how can i delete the old version, should the code auto delete the version and get new one to avoid this kind of problems? instead of deleting cache i mean

**Comment by wang-bin** [comment]
I also have a problem in logging, iirc the logging package used in fvp can print log to logcat, but now I can't see any fvp log recently

**Comment by abdelaziz-mahdy** [comment]
okay since i was testing locally flutter clean and pub cache where not deleting the mdk files, so i deleted them manually now it doesnt crash anymore, but do you think in cmake an mdk version check can be added? and download new version if the one found is not the latest? for easier debugging and to avoid this problem with other people too i think thats the safest option

**Comment by abdelaziz-mahdy** [comment]
i can confirm now that https://github.com/wang-bin/fvp/compare/master...impeller is working correctly , with impller on, it does lead to black screen when closing screen and reopen it, and with impller off it works even after closing screen and bringing it on.

**Comment by wang-bin** [comment]
> > I also have a problem in logging, iirc the logging package used in fvp can print log to logcat, but now I can't see any fvp log recently
> 
> in my apk, i didnt add the logging , or you mean internally it should show?

I add logging and tested yesterday.

> okay since i was testing locally flutter clean and pub cache where not deleting the mdk files, so i deleted them manually, but do you think in cmake an mdk version check can be added? and download new version if the one found is not the latest? for easier debugging and to avoid this problem with other people too i think thats the safest option

Maybe a fixed version is better. An ideal solution is pass an additional option to `flutter run` and `flutter build` to download the latest sdk, without the option use the version hardcoded in cmake

**Comment by wang-bin** [comment]
> i can confirm now that [master...impeller](https://github.com/wang-bin/fvp/compare/master...impeller) is working correctly , with impller on, it does lead to black screen when closing screen and reopen it, and with impller off it works even after closing screen and bringing it on.

Thanks for testing. What's your flutter version? Mine is 3.22, impeller shows nothing. When I tested with 3.19 before, i can see video.

**Comment by abdelaziz-mahdy** [comment]
> > > I also have a problem in logging, iirc the logging package used in fvp can print log to logcat, but now I can't see any fvp log recently
> > 
> > 
> > in my apk, i didnt add the logging , or you mean internally it should show?
> 
> I add logging and tested yesterday.
> 
> > okay since i was testing locally flutter clean and pub cache where not deleting the mdk files, so i deleted them manually, but do you think in cmake an mdk version check can be added? and download new version if the one found is not the latest? for easier debugging and to avoid this problem with other people too i think thats the safest option
> 
> Maybe a fixed version is better. An ideal solution is pass an additional option to `flutter run` and `flutter build` to download the latest sdk, without the option use the version hardcoded in cmake

let me know your plan and i can help update the cmakes to do it, maybe an env variable can help

**Comment by abdelaziz-mahdy** [comment]
> > i can confirm now that [master...impeller](https://github.com/wang-bin/fvp/compare/master...impeller) is working correctly , with impller on, it does lead to black screen when closing screen and reopen it, and with impller off it works even after closing screen and bringing it on.
> 
> Thanks for testing. What's your flutter version? Mine is 3.22, impeller shows nothing. When I tested with 3.19 before, i can see video.

i am using `3.22.2` using impller video works only if screen didnt close, if it closed no video get rendered

**Comment by wang-bin** [comment]
env is also a good idea.

> i am using 3.22.2 using impller video works only if screen didnt close, if it closed no video get rendered

ok, so that branch is better than no impeller support. I'm going to close this pr and merge that branch

**Pull request closed without merging**
