### PR TITLE
fix warning on android

### PR DESCRIPTION
**Pull request by abdelaziz-mahdy**
fixes https://github.com/wang-bin/fvp/issues/190

### CODE REVIEW

**Comment by AlexV525** [comment]
Changing this might cause older SDKs to fail to process with the callback.

**Comment by wang-bin** [comment]
You can rewrite java by gradle like [this commit](8fb6fd9), rename `onSurfaceAvailable` to `onSurfaceCreated` if flutterSdkVersionInt < 32700?

**Comment by abdelaziz-mahdy** [comment]
Oh okay I will do the changes in gradle then to support older sdks too

**Comment by abdelaziz-mahdy** [comment]
> You can edit java by gradle like [this commit](8fb6fd9), rename `onSurfaceAvailable` to `onSurfaceCreated` if flutterSdkVersionInt < 32700?

i did that, let me know if its correct

**Comment by wang-bin** [comment]
thanks, it works

**Pull request merged**
